[build]
    command = "next build"
    publish = ".next"

[[redirects]]
  from = "/"
  to = "/docs"
  status = 301
  force = true

  [[redirects]]
from = "/docs/ecosystem-roles/validator/*"
to = "https://docs.tangle.tools/docs/node/validator/requirements/"
status = 301
force = true

[[redirects]]
from = "/docs/tangle-network/*"
to = "https://docs.tangle.tools/"
status = 301
force = true
