name: publish

on:
  pull_request:
    branches: [ dev2 ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "echo NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install deps
        run: yarn install

      - name: Build documentation
        run: yarn build
      - name: Publish documentation
        run: |
          cd public
          git init
          echo '<meta http-equiv="refresh" content="0; url=http://docs.webb.tools/webb-docs/index.html">' > index.html
          git add .
          git -c user.name='ci' -c user.email='ci' commit -m 'Deploy documentation 🎩'
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages