name: publish

on:
  pull_request:
    branches: [ dev2 ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "echo NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages